### ISSUE TITLE
core-scroll: make scroll-direction configurable

### ISSUE THREAD

**Issue by markusv** [nrkno/core-components#109]
Consider adding a option to core-scroll for scroll direction. As of now core-scroll adds both horizontal and vertical scrolling, which is not always what you want. 

In tv.nrk.no we had a case where width and height are set as %. On some window sizes this trigger a rounding error in safari and do vertical scrolling.

**Comment by eirikbacker** [comment]
@markusv @janerikbr @formfett After extensive research, this is actually not a core-scroll issue. Adding `overflow-y: hidden` or only specifying `overflow-x: scroll` only makes things worse (making scroll traps in safari) 🤦‍♂️  The issue comes from Safari being inconsequent in rounding up or down half pixels (from thumbnail images in plugs). Example:
- Plug image is `16:9`, aka. `56.25%` padding-top
- The plug is rendered `128.48px` tall
- Parent element is rounded to `128px` tall

This causes there to actually be h `.4px` scroll opportunity, making safari kick in a "rubber-band" effect. Fortunately, there is a solution; set padding-bottom: 1px to your `.scroll-container__items-wrapper` and the issue should be resolved 💯 

I suggest we do not add this forced padding to core-scroll:
- this will cause (minimal, but) visual change to the page
- the consumer of core-scroll should be able to set padding themself
- the issue only occurs whenever there is half pixels inside a scrollable area
...but rather document the phenomenon. 👍 or 👎 ?

**Comment by eirikbacker** [comment]
Documented in https://static.nrk.no/core-components/latest/index.html?core-scroll/readme.md#nb-safari-bug
