### ISSUE TITLE
add support for custom elements

### ISSUE THREAD

**Issue by htor** [nrkno/core-components#169]
we need to research if we can export core components as custom elements so people can use things like `<core-toggle></core-toggle>` in their code.

**Comment by laat** [comment]
One downside with custom elements is that they are enforced to be global.

[NotSupportedError](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define#Exceptions) "When CustomElementRegistry already contains an entry with the same name or the same constructor (or is otherwise already defined)"

Which means that all apps on the page *must* use the same version if we use `<core-toggle>` as tag name.

I'm sure we can find workarounds

**Comment by eirikbacker** [comment]
Ah, indeed. Bummer. Let's try to figure something out. To be continued

**Comment by eirikbacker** [comment]
see related w3c discussion https://github.com/w3c/webcomponents/issues/716

**Comment by htor** [comment]
I WANT CUSTOM ELEMENTS NOW
