### ISSUE TITLE
core-dialog: backdrop click not working properly on Edge

### ISSUE THREAD

**Issue by astokke** [nrkno/core-components#299]
If I click the backdrop (or ESC) on Edge browser, the dialog will close but the backdrop remains visible so I can no longer interact with the page. 

Steps to reproduce: 

1) Go to https://static.nrk.no/core-components/latest/index.html?core-dialog/readme.md on Edge browser. 
2) Click 'Open dialog jsx'. 
3) Click the backdrop or hit ESC. 

Expected to close the dialog and hide the backdrop, but this will only close the dialog.

Also worth noting that if I click 'Open dialog' on the same page - the backdrop is not triggered at all. 

Clicking the Close dialog seems to be working as intended.

**Comment by eirikbacker** [comment]
😱  thanks for heads up! Fellesteam is unfortunately all out of office these days, but I'll try to investigate as this is quite major. There is a new branch in the making to reengineer backdrop all together due to #297. Also, after summer we will focus on getting automated Browser tests to avoid regression like this #300

**Comment by esseb** [comment]
It looks like the `onDialogToggle` callback doesn't get called either.
