### ISSUE TITLE
core-dialog: should remove backdrop on destroy

### ISSUE THREAD

**Issue by htor** [nrkno/core-components#346]
removing a `<core-dialog>` from the dom leaves behind its backdrop element. although the backdrop is hidden the dialog should instead remove the backdrop on destroy. right?

**Comment by eirikbacker** [comment]
Good point! Only issue might be costumers who wants to animate out the backdrop (for instance yr removes the dialog instead of hiding it when closing). Can an option be to only remove the backdrop if it was automatically generated, while leaving custom backdrops in place (making the consumer is responsible for the element they provided as backdrop? :))
